const content = {
  eng: {
    home: "Home",
    explore: "Explore",
    notification: "Notification",
    messages: "Messages",
    bookmarks: "Bookmarks",
    lists: "Lists",
    profile: "Profile",
    more: "More",
    trend: "Trends for you",
    like: "You might like",
    follow: "Follow",
    showmore: "Show more",
    whatsup: "What’s happening",
    search: "Search Twitter",
    terms: "Terms of service",
    policy: "Privacy Policy",
    cookie: "Cookie Policy",
    imprint: "Imprint",
    ads: "Ads Info",
  },
  ru: {
    home: "Главная страница",
    explore: "Исследовать",
    notification: "Уведомления",
    messages: "Сообщения",
    bookmarks: "Закладки",
    lists: "Списки",
    profile: "Профиль",
    more: "Более",
    trend: "Тенденции для вас",
    like: "Вам может понравиться",
    follow: "Следовать",
    showmore: "Показать еще",
    whatsup: "Что творится",
    search: "Искать в Twitter",
    terms: "Условия обслуживания",
    policy: "Политика конфиденциальности",
    cookie: "Политика использования файлов cookie",
    imprint: "Отпечаток",
    ads: "Информация о рекламе",
  },
};

export default content;
